//+------------------------------------------------------------------+
//|                                          {ea_name}.mq5            |
//|                        Generated by MT5 AI Bridge                 |
//|                https://github.com/faarh/mt5-ai-bridge            |
//+------------------------------------------------------------------+
#property copyright "MT5 AI Bridge"
#property link      "{server_url}"
#property version   "{version}"
#property description "Full-featured execution EA with command handling, trailing, breakeven"

#include <Trade/Trade.mqh>
CTrade trade;

//--- Inputs
input group "=== Bridge Settings ==="
input string   InpServerUrl     = "{server_url}";
input int      InpSyncInterval  = 2;
input bool     InpActive        = {is_active};
input int      InpMagic         = {magic};

input group "=== Risk ==="
input double   InpLotSize       = 0.1;
input int      InpSlPoints      = 0;
input int      InpTpPoints      = 0;
input int      InpMaxSpread     = 0;

input group "=== Data ==="
input int      InpCandleCount   = 100;
input int      InpTickCount     = 1000;
input bool     InpSendHistory   = true;
input bool     InpSendTicks     = true;
input int      InpBatchSize     = 50;

input group "=== Symbols ==="
input string   InpSymbols       = "{symbols}";

//--- Globals
datetime glLastSync = 0;
string   glSymbols[];
int      glSymbolCount = 0;
int      glMagic;
double   glPoint;
int      glTrailingStop = 0;
int      glTrailingStep = 0;
bool     glUseBreakeven = false;
int      glBreakevenPoints = 20;

//+------------------------------------------------------------------+
//| Expert initialization                                            |
//+------------------------------------------------------------------+
int OnInit()
{{
    trade.SetExpertMagicNumber(InpMagic);
    glMagic = InpMagic;
    glPoint = _Point;

    Print("MT5 AI Bridge EA v3 initialized. Server: ", InpServerUrl);

    if(StringLen(InpSymbols) < 1)
    {{
        Print("ERROR: No symbols configured");
        return INIT_FAILED;
    }}

    StringSplit(InpSymbols, ',', glSymbols);
    glSymbolCount = ArraySize(glSymbols);
    if(glSymbolCount < 1)
    {{
        Print("ERROR: No symbols configured");
        return INIT_FAILED;
    }}

    Print("Monitoring ", glSymbolCount, " symbols: ", InpSymbols);

    if(InpSendHistory)
    {{
        Sleep(1000);
        for(int i = 0; i < glSymbolCount; i++)
        {{
            string symbol = glSymbols[i];
            if(StringLen(symbol) < 1) continue;
            SendHistory(symbol);
            SendTicks(symbol);
        }}
    }}

    return(INIT_SUCCEEDED);
}}

//+------------------------------------------------------------------+
//| Expert tick function                                             |
//+------------------------------------------------------------------+
void OnTick()
{{
    datetime now = TimeCurrent();
    if(now - glLastSync < InpSyncInterval) return;

    for(int i = 0; i < glSymbolCount; i++)
    {{
        string symbol = glSymbols[i];
        if(StringLen(symbol) < 1) continue;

        double bid = SymbolInfoDouble(symbol, SYMBOL_BID);
        double ask = SymbolInfoDouble(symbol, SYMBOL_ASK);
        if(bid <= 0 || ask <= 0) continue;

        BroadcastTick(symbol, bid, ask);
        ApplyBreakeven(symbol);
        ApplyTrailing(symbol);
        ApplyGlobalTPSL(symbol);
    }}

    SyncWithServer();
    PollCommands();
    glLastSync = now;
}}

//+------------------------------------------------------------------+
//| Send historical candle data in bulk                              |
//+------------------------------------------------------------------+
void SendHistory(string symbol)
{{
    MqlRates candles[];
    ArraySetAsSeries(candles, true);
    if(CopyRates(symbol, _Period, 0, InpCandleCount, candles) < 1) return;

    int total = ArraySize(candles);
    int batches = (total + InpBatchSize - 1) / InpBatchSize;

    for(int b = 0; b < batches; b++)
    {{
        string payload = "[";
        int start = b * InpBatchSize;
        int end = MathMin(start + InpBatchSize, total);

        for(int i = start; i < end; i++)
        {{
            if(i > start) payload += ",";
            payload += StringFormat(
                "{{\\"type\\":\\"candle\\",\\"symbol\\":\\"%s\\",\\"open\\":%.5f,\\"high\\":%.5f,\\"low\\":%.5f,\\"close\\":%.5f,\\"volume\\":%I64d,\\"time\\":\\"%s\\",\\"digits\\":%d}}",
                symbol,
                candles[i].open, candles[i].high, candles[i].low, candles[i].close,
                (long)candles[i].tick_volume,
                TimeToString(candles[i].time, TIME_DATE|TIME_SECONDS),
                (int)_Digits
            );
        }}

        payload += "]";

        char post[], result[];
        string headers;
        StringToCharArray(payload, post);
        ArrayResize(post, ArraySize(post) - 1);

        string url = InpServerUrl + "/ea/bulk";
        ResetLastError();
        WebRequest("POST", url, "Content-Type: application/json\\r\\n", 3000, post, result, headers);
        Sleep(10);
    }}

    Print("Sent ", total, " candles in ", batches, " batches for ", symbol);
}}

//+------------------------------------------------------------------+
//| Send tick data in bulk                                           |
//+------------------------------------------------------------------+
void SendTicks(string symbol)
{{
    MqlRates ticks[];
    ArraySetAsSeries(ticks, true);
    if(CopyRates(symbol, PERIOD_M1, 0, InpTickCount, ticks) < 1) return;

    int total = ArraySize(ticks);
    int batches = (total + InpBatchSize - 1) / InpBatchSize;

    for(int b = 0; b < batches; b++)
    {{
        string payload = "[";
        int start = b * InpBatchSize;
        int end = MathMin(start + InpBatchSize, total);

        for(int i = start; i < end; i++)
        {{
            if(i > start) payload += ",";
            payload += StringFormat(
                "{{\\"type\\":\\"tick\\",\\"symbol\\":\\"%s\\",\\"open\\":%.5f,\\"high\\":%.5f,\\"low\\":%.5f,\\"close\\":%.5f,\\"volume\\":%I64d,\\"time\\":\\"%s\\",\\"digits\\":%d}}",
                symbol,
                ticks[i].open, ticks[i].high, ticks[i].low, ticks[i].close,
                (long)ticks[i].tick_volume,
                TimeToString(ticks[i].time, TIME_DATE|TIME_SECONDS),
                (int)_Digits
            );
        }}

        payload += "]";

        char post[], result[];
        string headers;
        StringToCharArray(payload, post);
        ArrayResize(post, ArraySize(post) - 1);

        string url = InpServerUrl + "/ea/bulk";
        ResetLastError();
        WebRequest("POST", url, "Content-Type: application/json\\r\\n", 3000, post, result, headers);
        Sleep(10);
    }}

    Print("Sent ", total, " ticks in ", batches, " batches for ", symbol);
}}

//+------------------------------------------------------------------+
//| Broadcast current tick to server                                 |
//+------------------------------------------------------------------+
void BroadcastTick(string symbol, double bid, double ask)
{{
    MqlRates rates[];
    ArraySetAsSeries(rates, true);
    if(CopyRates(symbol, _Period, 0, 1, rates) < 1) return;

    string payload = StringFormat(
        "{{\\"type\\":\\"live\\",\\"symbol\\":\\"%s\\",\\"open\\":%.5f,\\"high\\":%.5f,\\"low\\":%.5f,\\"close\\":%.5f,\\"bid\\":%.5f,\\"ask\\":%.5f,\\"digits\\":%d,\\"volume\\":%I64d,\\"time\\":\\"%s\\"}}",
        symbol,
        rates[0].open, rates[0].high, rates[0].low, rates[0].close,
        bid, ask,
        (int)_Digits,
        (long)rates[0].tick_volume,
        TimeToString(TimeCurrent(), TIME_DATE|TIME_SECONDS)
    );

    char post[], result[];
    string headers;
    StringToCharArray(payload, post);
    ArrayResize(post, ArraySize(post) - 1);

    string url = InpServerUrl + "/ea/tick";
    ResetLastError();
    WebRequest("POST", url, "Content-Type: application/json\\r\\n", 3000, post, result, headers);
}}

//+------------------------------------------------------------------+
//| Sync account info with server                                     |
//+------------------------------------------------------------------+
void SyncWithServer()
{{
    double balance = AccountInfoDouble(ACCOUNT_BALANCE);
    double equity = AccountInfoDouble(ACCOUNT_EQUITY);
    double margin = AccountInfoDouble(ACCOUNT_MARGIN);
    double profit = AccountInfoDouble(ACCOUNT_PROFIT);
    string company = AccountInfoString(ACCOUNT_COMPANY);
    long login = AccountInfoInteger(ACCOUNT_LOGIN);

    string payload = StringFormat(
        "{{\\"type\\":\\"account\\",\\"account\\":\\"%I64d\\",\\"broker\\":\\"%s\\",\\"balance\\":%.2f,\\"profit\\":%.2f,\\"equity\\":%.2f,\\"margin\\":%.2f,\\"magic\\":%d}}",
        login, company, balance, profit, equity, margin, glMagic
    );

    char post[], result[];
    string headers;
    StringToCharArray(payload, post);
    ArrayResize(post, ArraySize(post) - 1);

    string url = InpServerUrl + "/ea/tick";
    ResetLastError();
    int res = WebRequest("POST", url, "Content-Type: application/json\\r\\n", 3000, post, result, headers);
}}

//+------------------------------------------------------------------+
//| Poll for commands from server                                    |
//+------------------------------------------------------------------+
void PollCommands()
{{
    string url = InpServerUrl + "/ea/commands?magic=" + IntegerToString(glMagic);
    char result[];
    string headers;
    string response;

    ResetLastError();
    WebRequest("GET", url, "Accept: application/json\\r\\n", 3000, result, headers);

    if(ArraySize(result) > 0)
    {{
        StringToCharArray(response, result);
        ArrayResize(result, ArraySize(result) - 1);
        ExecuteCommands(response);
    }}
}}

//+------------------------------------------------------------------+
//| Execute commands from server                                     |
//+------------------------------------------------------------------+
void ExecuteCommands(string json)
{{
    string cmd = json;

    if(StringFind(cmd, ""action"":""close_all""") >= 0)
    {{
        CloseAllPositions();
    }}
    else if(StringFind(cmd, ""action"":""close""") >= 0)
    {{
        long ticket = StringToInteger(StringSubstr(cmd, StringFind(cmd, ""ticket"":") + 9));
        ClosePosition(ticket);
    }}
    else if(StringFind(cmd, ""action"":""set_sl""") >= 0)
    {{
        long ticket = StringToInteger(StringSubstr(cmd, StringFind(cmd, ""ticket"":") + 9));
        double sl = StringToDouble(StringSubstr(cmd, StringFind(cmd, ""sl"":") + 5));
        SetPositionSL(ticket, sl);
    }}
    else if(StringFind(cmd, ""action"":""set_tp""") >= 0)
    {{
        long ticket = StringToInteger(StringSubstr(cmd, StringFind(cmd, ""ticket"":") + 9));
        double tp = StringToDouble(StringSubstr(cmd, StringFind(cmd, ""tp"":") + 5));
        SetPositionTP(ticket, tp);
    }}
    else if(StringFind(cmd, ""action"":""trailing""") >= 0)
    {{
        glTrailingStop = StringToInteger(StringSubstr(cmd, StringFind(cmd, ""trailing_stop"":") + 15));
        glTrailingStep = StringToInteger(StringSubstr(cmd, StringFind(cmd, ""trailing_step"":") + 15));
    }}
    else if(StringFind(cmd, ""action"":""breakeven""") >= 0)
    {{
        glUseBreakeven = StringToInteger(StringSubstr(cmd, StringFind(cmd, ""enable"":") + 8)) > 0;
        glBreakevenPoints = StringToInteger(StringSubstr(cmd, StringFind(cmd, ""points"":") + 8));
    }}
    else if(StringFind(cmd, ""action"":""buy""") >= 0)
    {{
        double lot = StringToDouble(StringSubstr(cmd, StringFind(cmd, ""lot"":") + 5));
        double sl = StringToDouble(StringSubstr(cmd, StringFind(cmd, ""sl"":") + 5));
        double tp = StringToDouble(StringSubstr(cmd, StringFind(cmd, ""tp"":") + 5));
        string symbol = StringSubstr(cmd, StringFind(cmd, ""symbol"":""") + 10);
        symbol = StringSubstr(symbol, 0, StringFind(symbol, """"") - 1);
        double ask = SymbolInfoDouble(symbol, SYMBOL_ASK);
        if(ask > 0) trade.Buy(lot, symbol, ask, sl > 0 ? sl : 0, tp > 0 ? tp : 0, ""Strategy Buy"");
    }}
    else if(StringFind(cmd, ""action"":""sell""") >= 0)
    {{
        double lot = StringToDouble(StringSubstr(cmd, StringFind(cmd, ""lot"":") + 5));
        double sl = StringToDouble(StringSubstr(cmd, StringFind(cmd, ""sl"":") + 5));
        double tp = StringToDouble(StringSubstr(cmd, StringFind(cmd, ""tp"":") + 5));
        string symbol = StringSubstr(cmd, StringFind(cmd, ""symbol"":""") + 10);
        symbol = StringSubstr(symbol, 0, StringFind(symbol, """"") - 1);
        double bid = SymbolInfoDouble(symbol, SYMBOL_BID);
        if(bid > 0) trade.Sell(lot, symbol, bid, sl > 0 ? sl : 0, tp > 0 ? tp : 0, ""Strategy Sell"");
    }}
}}

//+------------------------------------------------------------------+
//| Close all positions                                              |
//+------------------------------------------------------------------+
void CloseAllPositions()
{{
    for(int i = 0; i < glSymbolCount; i++)
    {{
        string symbol = glSymbols[i];
        if(StringLen(symbol) < 1) continue;

        PositionsTotal();
        for(int pos = PositionsTotal() - 1; pos >= 0; pos--)
        {{
            if(PositionGetSymbol(pos) == symbol)
            {{
                trade.PositionClose(PositionGetTicket(pos));
            }}
        }}
    }}
}}

//+------------------------------------------------------------------+
//| Close specific position                                          |
//+------------------------------------------------------------------+
void ClosePosition(long ticket)
{{
    trade.PositionClose(ticket);
}}

//+------------------------------------------------------------------+
//| Set position SL                                                  |
//+------------------------------------------------------------------+
void SetPositionSL(long ticket, double sl)
{{
    trade.PositionModify(ticket, sl, PositionGetDouble(POSITION_TP));
}}

//+------------------------------------------------------------------+
//| Set position TP                                                  |
//+------------------------------------------------------------------+
void SetPositionTP(long ticket, double tp)
{{
    trade.PositionModify(ticket, PositionGetDouble(POSITION_SL), tp);
}}

//+------------------------------------------------------------------+
//| Apply breakeven logic                                            |
//+------------------------------------------------------------------+
void ApplyBreakeven(string symbol)
{{
    if(!glUseBreakeven || glBreakevenPoints <= 0) return;

    for(int i = 0; i < PositionsTotal(); i++)
    {{
        if(PositionGetSymbol(i) != symbol) continue;

        double sl = PositionGetDouble(POSITION_SL);
        double open_price = PositionGetDouble(POSITION_PRICE_OPEN);
        double current_price = PositionGetDouble(POSITION_PRICE_CURRENT);
        long ticket = PositionGetTicket(i);

        if(sl == 0 || (sl < open_price && current_price > open_price + glBreakevenPoints * _Point))
        {{
            trade.PositionModify(ticket, open_price + 1 * _Point, PositionGetDouble(POSITION_TP));
        }}
    }}
}}

//+------------------------------------------------------------------+
//| Apply trailing stop                                              |
//+------------------------------------------------------------------+
void ApplyTrailing(string symbol)
{{
    if(glTrailingStop <= 0) return;

    for(int i = 0; i < PositionsTotal(); i++)
    {{
        if(PositionGetSymbol(i) != symbol) continue;

        double sl = PositionGetDouble(POSITION_SL);
        double open_price = PositionGetDouble(POSITION_PRICE_OPEN);
        double current_price = PositionGetDouble(POSITION_PRICE_CURRENT);
        long ticket = PositionGetTicket(i);
        long type = PositionGetInteger(POSITION_TYPE);
        double new_sl = sl;

        if(type == POSITION_TYPE_BUY)
        {{
            double trail_level = current_price - glTrailingStop * glPoint;
            if(sl == 0 || sl < trail_level)
            {{
                new_sl = trail_level + glTrailingStep * glPoint;
                if(new_sl > sl + glPoint)
                {{
                    trade.PositionModify(ticket, new_sl, PositionGetDouble(POSITION_TP));
                }}
            }}
        }}
        else if(type == POSITION_TYPE_SELL)
        {{
            double trail_level = current_price + glTrailingStop * glPoint;
            if(sl == 0 || sl > trail_level)
            {{
                new_sl = trail_level - glTrailingStep * glPoint;
                if(new_sl < sl - glPoint || sl == 0)
                {{
                    trade.PositionModify(ticket, new_sl, PositionGetDouble(POSITION_TP));
                }}
            }}
        }}
    }}
}}

//+------------------------------------------------------------------+
//| Apply global TP/SL if configured                                 |
//+------------------------------------------------------------------+
void ApplyGlobalTPSL(string symbol)
{{
    if(InpSlPoints <= 0 && InpTpPoints <= 0) return;

    for(int i = 0; i < PositionsTotal(); i++)
    {{
        if(PositionGetSymbol(i) != symbol) continue;

        double sl = PositionGetDouble(POSITION_SL);
        double tp = PositionGetDouble(POSITION_TP);
        double open_price = PositionGetDouble(POSITION_PRICE_OPEN);
        long type = PositionGetInteger(POSITION_TYPE);
        double new_sl = sl;
        double new_tp = tp;

        if(type == POSITION_TYPE_BUY)
        {{
            if(InpSlPoints > 0 && (sl == 0 || sl < open_price - InpSlPoints * glPoint))
                new_sl = open_price - InpSlPoints * glPoint;
            if(InpTpPoints > 0 && tp == 0)
                new_tp = open_price + InpTpPoints * glPoint;
        }}
        else if(type == POSITION_TYPE_SELL)
        {{
            if(InpSlPoints > 0 && (sl == 0 || sl > open_price + InpSlPoints * glPoint))
                new_sl = open_price + InpSlPoints * glPoint;
            if(InpTpPoints > 0 && tp == 0)
                new_tp = open_price - InpTpPoints * glPoint;
        }}

        if(new_sl != sl || new_tp != tp)
        {{
            trade.PositionModify(PositionGetTicket(i), new_sl, new_tp);
        }}
    }}
}}

//+------------------------------------------------------------------+
//| Expert deinitialization                                          |
//+------------------------------------------------------------------+
void OnDeinit(const int reason)
{{
    Print("MT5 AI Bridge EA stopped.");
}}
